apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccountName | default .Release.Name }}
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  annotations:
    azure.workload.identity/client-id: {{ .Values.serviceAccount.annotations.azure\.workload\.identity/client-id }}
  labels:
    app: {{ .Release.Name }}
    azure.workload.identity/use: "true" 